version: "3.8"

services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000" # For JNLP agent connections
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

